version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout

      # Install Dependencies
      - run: npm install

      # Run Jest tests
      - run: npm run test
  deploy:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - run:
          name: Deploy Main to Heroku
          command: |
            git push https://$HEROKU_API_KEY@heroku.com/$HEROKU_APP_NAME.git main

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main